/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package premiere.pkginterface.graphique.pommarel;

/**
 *
 * @author quent
 */
public class Fenetre_principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre_principale
     */
    public Fenetre_principale() {
        initComponents();
        label_bonnerep.setVisible(false);
        label_mauvaiserep.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_premierequestion = new javax.swing.JLabel();
        label_question = new javax.swing.JLabel();
        Button_bonnerep = new javax.swing.JButton();
        button_mauvaiserep1 = new javax.swing.JButton();
        button_mauvaiserep2 = new javax.swing.JButton();
        label_bonnerep = new javax.swing.JLabel();
        label_mauvaiserep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_premierequestion.setText("Première question");

        label_question.setText(" Combien mesure t-il d'iphone ?");

        Button_bonnerep.setText("14 iphone");
        Button_bonnerep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_bonnerepActionPerformed(evt);
            }
        });

        button_mauvaiserep1.setText("18 iphone");
        button_mauvaiserep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mauvaiserep1ActionPerformed(evt);
            }
        });

        button_mauvaiserep2.setText("23 iphone");
        button_mauvaiserep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mauvaiserep2ActionPerformed(evt);
            }
        });

        label_bonnerep.setText("Bonne réponse");

        label_mauvaiserep.setText("Mauvaise réponse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(Label_premierequestion))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_bonnerep)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(label_question)
                        .addGap(55, 55, 55)
                        .addComponent(button_mauvaiserep2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_mauvaiserep)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_bonnerep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_mauvaiserep1))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_premierequestion)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_question, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_mauvaiserep2)
                            .addComponent(button_mauvaiserep1)
                            .addComponent(Button_bonnerep))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_bonnerep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_mauvaiserep)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_bonnerepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_bonnerepActionPerformed
label_bonnerep.setVisible(true);
label_mauvaiserep.setVisible(false);

    }//GEN-LAST:event_Button_bonnerepActionPerformed

    private void button_mauvaiserep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mauvaiserep2ActionPerformed
label_mauvaiserep.setVisible(true);
label_bonnerep.setVisible(false);
    }//GEN-LAST:event_button_mauvaiserep2ActionPerformed

    private void button_mauvaiserep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mauvaiserep1ActionPerformed
label_mauvaiserep.setVisible(true);
label_bonnerep.setVisible(false);

    }//GEN-LAST:event_button_mauvaiserep1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_bonnerep;
    private javax.swing.JLabel Label_premierequestion;
    private javax.swing.JButton button_mauvaiserep1;
    private javax.swing.JButton button_mauvaiserep2;
    private javax.swing.JLabel label_bonnerep;
    private javax.swing.JLabel label_mauvaiserep;
    private javax.swing.JLabel label_question;
    // End of variables declaration//GEN-END:variables
}
